### ISSUE TITLE
Launchmany is currently failing

### ISSUE THREAD

**Issue by Zac-HD** [ANU-WALD/fire-data-processing#21] opened 2018-02-02 04:16 UTC
I don't know why, but the logs are in `/g/data/xc0/project/FMC_Australia/logs/`.  Good luck!

(I'm sorry 😭)

**Comment by kingdion** [comment] 2018-02-07 00:38
Not sure if I fixed the bug - but it's not failing Travis anymore. (missing type annotation fixed)

**Comment by Zac-HD** [comment] 2018-02-07 01:20
Unfortunately it's worse than that - running `source activate rs3 ; python launchmany,py` will be OK, but then the launched jobs all die.  Not sure why, though the logs should help, but annotations don't have that kind of effect at runtime 😢

**Comment by kingdion** [comment] 2018-02-07 03:17
I can't access the logs to look into it (I'm assuming I don't have read perms). I thought launchmany might have failed because the mypy test didn't pass.

**Comment by cjtapper** [comment] 2018-02-14 02:22
I don't seem to have read permissions either, I will see if Albert can change them.

**Comment by cjtapper** [comment] 2018-02-14 02:54
```
ERROR: Bad job ID in authorisation

======================================================================================
                  Resource Usage on 2018-02-14 13:50:13:
   Job Id:             4100513.r-man2
   Project:            xc0
   Exit Status:        1
   Service Units:      0.06
   NCPUs Requested:    1                      NCPUs Used: 1               
                                           CPU Time Used: 00:00:00                                   
   Memory Requested:   20.0GB                Memory Used: 0B              
   Walltime requested: 01:00:00            Walltime Used: 00:02:43        
   JobFS requested:    500.0MB                JobFS used: 0B              
======================================================================================
```

**Comment by cjtapper** [comment] 2018-02-14 04:08
I've submitted a help request with NCI, since I can't find any documentation on this particular error.

**Comment by cjtapper** [comment] 2018-02-14 06:23
![screenshot from 2018-02-14 17-21-37](https://user-images.githubusercontent.com/5920765/36190312-94e13760-11ab-11e8-8a22-51c43000abb1.png)
This could be our problem. I've queued up some jobs manually for single tiles, if they work I'll try removing the quotation marks in launch_many.py

**Comment by cjtapper** [comment] 2018-02-15 00:33
Okay, so this fixed one problem, but there seems to be an issue with `onetile.py`

```python
if satellite == 'MODIS':
        bands = xr.concat([dataset[b] for b in bands_to_use[satellite]],
                          dim='band')
```

After the `xr.concat` here, the resulting `DataArray` no longer has the `x` and `y` coordinates.

```
<xarray.Dataset>
Dimensions:          (XDim:MOD_Grid_BRDF: 2400, YDim:MOD_Grid_BRDF: 2400, time: 2, x: 2400, y: 2400)
Coordinates:
  * time             (time) datetime64[ns] 2017-01-01 2017-01-05
  * x                (x) float64 1.112e+07 1.112e+07 1.112e+07 1.112e+07 ...
  * y                (y) float64 -4.448e+06 -4.448e+06 -4.449e+06 -4.449e+06 ...
Dimensions without coordinates: XDim:MOD_Grid_BRDF, YDim:MOD_Grid_BRDF
Data variables:
    red_630_690      (time, YDim:MOD_Grid_BRDF, XDim:MOD_Grid_BRDF) float32 dask.array<shape=(2, 2400, 2400), chunksize=(1, 2400, 2400)>
    nir1_780_900     (time, YDim:MOD_Grid_BRDF, XDim:MOD_Grid_BRDF) float32 dask.array<shape=(2, 2400, 2400), chunksize=(1, 2400, 2400)>
    blue_450_520     (time, YDim:MOD_Grid_BRDF, XDim:MOD_Grid_BRDF) float32 dask.array<shape=(2, 2400, 2400), chunksize=(1, 2400, 2400)>
    green_530_610    (time, YDim:MOD_Grid_BRDF, XDim:MOD_Grid_BRDF) float32 dask.array<shape=(2, 2400, 2400), chunksize=(1, 2400, 2400)>
    nir2_1230_1250   (time, YDim:MOD_Grid_BRDF, XDim:MOD_Grid_BRDF) float32 dask.array<shape=(2, 2400, 2400), chunksize=(1, 2400, 2400)>
    swir1_1550_1750  (time, YDim:MOD_Grid_BRDF, XDim:MOD_Grid_BRDF) float32 dask.array<shape=(2, 2400, 2400), chunksize=(1, 2400, 2400)>
    swir2_2090_2350  (time, YDim:MOD_Grid_BRDF, XDim:MOD_Grid_BRDF) float32 dask.array<shape=(2, 2400, 2400), chunksize=(1, 2400, 2400)>
    ndvi_ok_mask     (time, YDim:MOD_Grid_BRDF, XDim:MOD_Grid_BRDF) bool dask.array<shape=(2, 2400, 2400), chunksize=(1, 2400, 2400)>
    ndii             (time, YDim:MOD_Grid_BRDF, XDim:MOD_Grid_BRDF) float32 dask.array<shape=(2, 2400, 2400), chunksize=(1, 2400, 2400)>
```

After (bands DataArray):
```
<xarray.DataArray 'red_630_690' (band: 6, time: 2, YDim:MOD_Grid_BRDF: 2400, XDim:MOD_Grid_BRDF: 2400)>
dask.array<shape=(6, 2, 2400, 2400), dtype=float32, chunksize=(1, 1, 2400, 2400)>
Coordinates:
  * time     (time) datetime64[ns] 2017-01-01 2017-01-05
Dimensions without coordinates: band, YDim:MOD_Grid_BRDF, XDim:MOD_Grid_BRDF
```

This causes an exception at line 115 of `onetile.py` because `x` and `y` don't exist.
`cond = np.logical_and(ok, mask[:bands.y.size, :bands.x.size]).values`

@Zac-HD Any idea how to fix this? Still don't have my head entirely around this xarray stuff. I think we need to re-add coordinates or something?

**Comment by Zac-HD** [comment] 2018-02-15 00:44
Oops - looks like each MODIS product uses a different name for the `x` and `y` coordinates, which I broke in 990f56e8025800a8af568381856304241d45caa1 (really: d7297910f7a9febce65d6fc33d0c12ff564e9ddf).  Once you revert the "helpful" refactoring, the problem -
 that the data doesn't have `x` and `y` coords before concatenating either - should go away.

Once that's sorted, you can but shouldn't need to call `modis.add_tile_coords` on the bands DataArray.

**Comment by cjtapper** [comment] 2018-02-19 03:36
Closed as the remaining issues are caused by onetile.py exceeding the allocated walltime (see #22 )

**Closed** 2018-02-19 03:35 UTC
